#!/bin/bash

path="${1:-.}"
file="${2:-README}"
extension="${3:-md}"
watermark_status="${4:-original}"
watermark_msg=$5

# Install helm-docs
echo -e "\nInstalling helm-docs\n"
curl -L "https://github.com/norwoodj/helm-docs/releases/download/v1.5.0/helm-docs_1.5.0_Linux_x86_64.tar.gz" -o $path/helm-docs.tar.gz
tar -xzf $path/helm-docs.tar.gz helm-docs


# Execute helm-docs
./helm-docs


# Capture in array all path files.
array=()
while IFS=  read -r -d $'\0'; do
    array+=("$REPLY")
done < <(find ./charts/ -iname "$find.$extension" -print0)


# Delete Watermark
function watermark_delete {
for i in "${array[@]}"
  do
    while read -r line
    do
      [[ ! $line =~ "Autogenerated" ]] && echo "$line"
    done <$i > o
    mv o $i
done
}


# Replace Watermark
function watermark_replace {
for i in "${array[@]}"
  do
    echo $watermark_msg >> $i
done
}


# Print list all path fles in charts.
echo -e "\nList off all path files"
printf '%s\n' "${array[@]}"

if [[ "$watermark_status" = false ]]
  then
    watermark_delete
elif [[ "$watermark_status" = true ]]
  then
    watermark_delete
    watermark_replace
elif [[ "$watermark_status" = "original" ]]
  then
    echo ""
fi

